default: &default
  adapter:    mysql2
  encoding:   utf8
  collation:  utf8_general_ci
  pool:       5
  host:       <%= ENV.fetch('DATABASE_HOST', '130.211.48.74') %>
  username:   <%= ENV.fetch('DATABASE_USER', 'development') %>
  password:   <%= ENV.fetch('DATABASE_PASSWORD', 'trc2020!') %>

development:
  <<: *default
  database: applogic_production

test:
  <<: *default
  database: applogic_production

production:
  <<: *default
  url:      <%= ENV['DATABASE_URL'] %>
  pool:     10
  database: <%= ENV.fetch('DATABASE_NAME', 'applogic_production') %>
